### ISSUE TITLE
Mark homework1, exercise1&2 of Yuhui Wang

### ISSUE THREAD

**Issue by ywangflora** [ywangflora/stat679work#2]
@cecileane 

SHA:https://github.com/ywangflora/stat679work/commit/1d5c81a1a5586c899374a0bc51309728b7982f46

Hi professor,

I'm Yuhui Wang who elected your 679-1 course this semester. The SHA above shows the first homework of exercise1&2 I have done. The homework contains 2 shell script file, 1 csv file and 1 readme markdown file.

Best,

Yuhui Wang

**Comment by cecileane** [comment]
Hi Yuhui,
Nice work! You have a clever use of `cut` to extract the root name from the full file name with its path.

In your script to normalize the file names, it would have been better to use `timetest${number}_snaq.log` instead of `timetest$number\_snaq.log` (4 similar instances). I suggested that you do so in my previous feedback on this [issue](https://github.com/ywangflora/stat679work/issues/1). Please use my feedback to learn better coding practices. Here, the very important coding practice with shell variables is to access their value with `${number}` instead of `$number`. It's a very good practice generally.

In your normalization script, your coding style is not very good:
- no indentation within the `do` `done` block in the first loop
- no newlines and no indentation in the second loop.

Coding style is better in your second script, but `do` and `done` should not be indented (all the lines inside should be, and are).

In your script to summarize the results, you should use pipes instead of assigning variables, like here:

``` shell
o=`echo ./out/$analysis\.out` # get the relative path to the out file
c=`grep 'Elapsed\stime' $o | grep -oE "\d+\.\d+"`
```

instead it would be best to use a pipe:

``` shell
c=`echo ./out/$analysis\.out | grep 'Elapsed\stime' $o | grep -oE "\d+\.\d+"`
```

or much simpler actually:

``` shell
c=`grep 'Elapsed\stime' ./out/$analysis\.out | grep -oE "\d+\.\d+"`
```

Your csv file should _not_ have spaces after commas. The commas are used to separate the columns, not spaces. Spaces become part of the entry values then, which is not good.

I could reproduce the results, which was great.

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.
