### ISSUE TITLE
Mark homework 1, exercise 3 of Yuhui Wang

### ISSUE THREAD

**Issue by ywangflora** [ywangflora/stat679work#3]
Hi professor,

The following is my homework on exercise3. It contains three files called 'summarizeSNaQres2.csv' , 'summarySNaQres2.sh' and 'readme.md'.

Best,

Yuhui Wang

@cecileane
SHA: adca2ce

**Comment by cecileane** [comment]
Thanks Yuhui! This is my way of asking Zach (@kingcohn1) and Peigen (@BaconZhou) to try your script and provide feedback on it.

**Comment by BaconZhou** [comment]
Hi, Yuhui, 

The script is neat, and nice strategy to use `basename`, `gsed`,`for`. We also share the same thought using `cut` to do the loglink question, so that it save me some time to think about it.

Maybe more documentation will be better? Although I see your readme file has the instruction for `log/` and `out/` directories arrangement, and we can see the right place from the code directly, it still will be helpful if there can be more details.

Overall, it is a nice scripts!

Best,
Peigen

**Comment by zpcohen** [comment]
Hello Yuhui,

Nice script! As Peigen said you use `basename, gsed,` and `for` nicely. But Dr. Ané suggested we start every script with: 

``` shell
#!/bin/bash
set -e # script terminates if any command exits with non-zero status
set -u # terminates if any variable is unset
set -o pipefail # terminates if command within a pipes exits unsuccessfully
```

This ensures your commands run properly and prevents any errors from accumulating. I would also recommend throwing an `echo` command after a your first loop of variable setting, and after the first `$loglik if` loop, which should also have a comment about what an `if` statement is. I appreciated the overall layout of this script as it was easy to read and follow. Nice and neat! 

Best,
Zach
