### ISSUE TITLE
Stat 679-1 HW2 submission

### ISSUE THREAD

**Issue by ywangflora** [ywangflora/stat679work#4]
Hi professor,

The following is my solution on hw2. It contains five files called 'hw2_code.py' , 'waterTemperature.csv', 'energy.csv', 'output_hw2.csv' and 'readme.md'.

Best,

Yuhui Wang

SHA:
<https://github.com/ywangflora/stat679work/commit/e9cf65ddb05a70aba13be09d702ca49c6f5fc653>
@cecileane

**Comment by cecileane** [comment]
Hi Yuhui,

Very nice job! More details below.

## overall presentation

You have a great readme file. I like how you explain what your function does, and what assumptions it checks. That's great. You have a good use of markdown style. You could have used a large code block to show the script usage: like this (between a pair of 3 backticks):

```shell
python hw2_code.py waterTemperature.csv energy.csv
```

instead of this (between a pair of single backticks): `python hw2_code.py waterTemperature.csv energy.csv`. Just fyi.

It would have been best to organize your files with separate directories for your script and for your data / result files.

## running your script

Calling your script with a wrong number of arguments or in the wrong order gives unhelpful error messages (see below). If you had used the argparse module, you could have improved the helpfulness of error messages.

```shell
$ python hw2_code.py
Traceback (most recent call last):
  File "hw2_code.py", line 79, in <module>
    openfile(sys.argv[1],sys.argv[2])
IndexError: list index out of range

$ python hw2_code.py energy.csv waterTemperature.csv
the time is not all 00:00:00
the time is not all 00:00:00
...
the time is not all 00:00:00
the time is not all 00:00:00
Traceback (most recent call last):
  File "hw2_code.py", line 79, in <module>
    openfile(sys.argv[1],sys.argv[2])
  File "hw2_code.py", line 52, in openfile
    split_water[1] = time.strptime(split_water[1],'%m/%d/%y %I:%M:%S %p') # change the waterTemperature time to strptime with time modulus
  File "/Users/ane/anaconda/lib/python3.5/_strptime.py", line 504, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/Users/ane/anaconda/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '9468' does not match format '%m/%d/%y %I:%M:%S %p'
```

Your script ran successfully with the correct arguments, but the output had extra commas and a repeated energy column (including for the header), like this:

    "#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)","Energy Produced (kWh)","Energy Produced (kWh)"/1000
    1,07/29/16 10:26:34 AM,72.86,,
    2,07/29/16 11:26:34 AM,73.92,,
    3,07/29/16 12:26:34 PM,73.98,,
    13,07/29/16 10:26:34 PM,73.27,,
    14,07/29/16 11:26:34 PM,73.45,9468,9.468
    15,07/30/16 12:26:34 AM,72.30,,
    16,07/30/16 01:26:34 AM,72.70,,

instead of this:

    "#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)","Energy Produced (kWh)"
    1,07/29/16 10:26:34 AM,72.86,
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,
    16,07/30/16 01:26:34 AM,72.70,

The first energy column was not needed (it's in Wh by the way, not kWh, and your second energy column is in Wh/1000 = kWh). But I see the logic of having both columns, as they differ by the 1000 factor.

## about your code

Very nice use of the `time` module! If the data file change format for any reason, this use of the time module will make it easy to adapt the script to any new time format.

It would have been best to break your code down into several function. You have only one function, `openfile`, whose name is not descriptive of what the function does (it does a whole lot more than opening a file!!). Your function has a docstring, which is great to explain what the function does.

Your line 73 with `with open("output_hw2.csv", 'a') as fh:` is not needed: it comes right after a block where this file is already opened for writing.

Nice use of regular expressions for checking that the energy times are at midnight :)

You can go ahead and close this issue now. Thanks!
